In [3]:
import gym
import crafter

env = gym.make('CrafterReward-v1')  # Or CrafterNoReward-v1
env = crafter.Recorder(
  env, './data/crafter',
  save_stats=True,
  save_video=False,
  save_episode=False,
)

obs = env.reset()
done = False
while not done:
  action = env.action_space.sample()
  obs, reward, done, info = env.step(action)


/home/deadscholar/miniconda3/envs/rllib/lib/python3.10/site-packages/crafter/engine.py:126: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  image = imageio.imread(filename.read_bytes())
/home/deadscholar/miniconda3/envs/rllib/lib/python3.10/site-packages/crafter/worldgen.py:12: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  tunnels = np.zeros(world.area, np.bool)


In [4]:
env = gym.make('CrafterReward-v1')  # Or CrafterNoReward-v1
env = crafter.Recorder(
  env, './data/crafter',
  save_stats=False,
  save_video=False,
  save_episode=False,
)

obs = env.reset()
done = False

In [6]:
action = env.action_space.sample()
obs, reward, done, info = env.step(action)
print(obs)
print(reward)
print(done)
print(info)

[[[ 29 168  12]
  [ 21 142  26]
  [ 21 142  26]
  ...
  [ 21 142  26]
  [ 21 142  26]
  [  0   0   0]]

 [[ 29 168  12]
  [ 21 142  26]
  [ 21 142  26]
  ...
  [ 29 168  12]
  [ 21 142  26]
  [  0   0   0]]

 [[ 29 168  12]
  [ 21 142  26]
  [ 21 142  26]
  ...
  [ 29 168  12]
  [ 21 142  26]
  [  0   0   0]]

 ...

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]]
0.0
False
{'inventory': {'health': 9, 'food': 9, 'drink': 9, 'energy': 9, 'sapling': 0, 'wood': 0, 'stone': 0, 'coal': 0, 'iron': 0, 'diamond': 0, 'wood_pickaxe': 0, 'stone_pickaxe': 0, 'iron_pickaxe': 0, 'wood_sword': 0, 'stone_sword': 0, 'iron_sword': 0}, 'achievements': {'collect_coal': 0, 'collect_diamond': 0, 'collect_drink': 0, 'collect_iron': 0, 'collect_saplin

In [7]:
obs.shape

(64, 64, 3)

In [13]:
for _ in range(100):
    print(env.observation_space)

Box(0, 255, (64, 64, 3), uint8)
Box(0, 255, (64, 64, 3), uint8)
Box(0, 255, (64, 64, 3), uint8)
Box(0, 255, (64, 64, 3), uint8)
Box(0, 255, (64, 64, 3), uint8)
Box(0, 255, (64, 64, 3), uint8)
Box(0, 255, (64, 64, 3), uint8)
Box(0, 255, (64, 64, 3), uint8)
Box(0, 255, (64, 64, 3), uint8)
Box(0, 255, (64, 64, 3), uint8)
Box(0, 255, (64, 64, 3), uint8)
Box(0, 255, (64, 64, 3), uint8)
Box(0, 255, (64, 64, 3), uint8)
Box(0, 255, (64, 64, 3), uint8)
Box(0, 255, (64, 64, 3), uint8)
Box(0, 255, (64, 64, 3), uint8)
Box(0, 255, (64, 64, 3), uint8)
Box(0, 255, (64, 64, 3), uint8)
Box(0, 255, (64, 64, 3), uint8)
Box(0, 255, (64, 64, 3), uint8)
Box(0, 255, (64, 64, 3), uint8)
Box(0, 255, (64, 64, 3), uint8)
Box(0, 255, (64, 64, 3), uint8)
Box(0, 255, (64, 64, 3), uint8)
Box(0, 255, (64, 64, 3), uint8)
Box(0, 255, (64, 64, 3), uint8)
Box(0, 255, (64, 64, 3), uint8)
Box(0, 255, (64, 64, 3), uint8)
Box(0, 255, (64, 64, 3), uint8)
Box(0, 255, (64, 64, 3), uint8)
Box(0, 255, (64, 64, 3), uint8)
Box(0, 2